version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: logitrack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Senha do usuário root
      MYSQL_DATABASE: logitrack
    ports:
      - "3306:3306" # Porta do PC : Porta do Container
    volumes:
      - db_data:/var/lib/mysql # Salva os dados mesmo se desligar o PC
    command: --max_allowed_packet=64M # Configuração vital para seus BLOBs de imagem!

volumes:
  db_data: