services:
  db-logitrack:
    image: mysql:8.0
    container_name: mysql-logitrack
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logitrack
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Se vocÃª tiver um script SQL na pasta, descomente a linha abaixo:
      - ./script.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --max_allowed_packet=64M
    networks:
      - logitrack-net

  backend-logitrack:
    build: .
    container_name: java-backend
    depends_on:
      - db-logitrack
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-logitrack:3306/logitrack?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - logitrack-net


volumes:
  db_data:

networks:
  logitrack-net:
    driver: bridge